# Generated by Django 4.2.2 on 2023-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_guests',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
