# Generated by Django 4.2.7 on 2023-11-28 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_remove_booking_number_guests_alter_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('deleted', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('pets', models.BooleanField(default=True)),
                ('price_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='photos/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_booking',
            field=models.CharField(choices=[('C', 'confirmed'), ('P', 'pending'), ('R', 'rejected'), ('IP', 'inprogress')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='housing',
            name='photos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housings', to='bookings.photo'),
        ),
        migrations.AddField(
            model_name='housing',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='housings', to='bookings.service'),
        ),
        migrations.AddField(
            model_name='housing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.housing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookings.housing'),
            preserve_default=False,
        ),
    ]
